workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Create local.properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Grant permission to gradlew
        script: chmod +x android/gradlew
      - name: Build APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
